version: '3'
services:
 web:
    image: nginx:alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend:/frontend
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8800:80"